# Generated by Django 3.0.7 on 2021-07-06 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='book_pics')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
