# Generated by Django 3.0.7 on 2021-07-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20210707_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.IntegerField(choices=[(0, 'Regular'), (1, 'Manager'), (2, 'Admin')], default=0),
        ),
    ]
