# Generated by Django 3.0.7 on 2021-07-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_book_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.IntegerField(choices=[(0, 'CS'), (1, 'Non-CS'), (2, 'Common')], default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.IntegerField(choices=[(0, 'English'), (1, 'Hindi'), (2, 'German'), (3, 'English(U.S.)'), (4, 'English(India)')], default=0),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
