# Generated by Django 3.0.7 on 2021-07-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20210707_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.IntegerField(choices=[(0, 'CS'), (1, 'Non-CS'), (2, 'Common')], null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.IntegerField(choices=[(0, 'English'), (1, 'Hindi'), (2, 'German'), (3, 'English(U.S.)'), (4, 'English(India)')], null=True),
        ),
    ]
