# Generated by Django 3.0.7 on 2021-07-10 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20210707_1509'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('name', 'author', 'genre', 'language')},
        ),
    ]
